/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MyDslIdeModule /* implements AbstractMyDslIdeModule  */{
}
