/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.xtext.example.mydsl.tests.MyDslInjectorProvider;

@ExtendWith(InjectionExtension.class)
@InjectWith(MyDslInjectorProvider.class)
@SuppressWarnings("all")
public class MyDslParsingTest {
  @Inject
  private /* ParseHelper<Solid> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field MyDslParsingTest.parseHelper refers to the missing type Solid"
      + "\nname cannot be resolved"
      + "\nfacets cannot be resolved"
      + "\nnormal cannot be resolved"
      + "\ngetX1 cannot be resolved"
      + "\ngetX2 cannot be resolved"
      + "\ngetX3 cannot be resolved"
      + "\ngetV1 cannot be resolved"
      + "\ngetX1 cannot be resolved"
      + "\ngetX2 cannot be resolved"
      + "\ngetX3 cannot be resolved"
      + "\ngetV2 cannot be resolved"
      + "\ngetX1 cannot be resolved"
      + "\ngetX2 cannot be resolved"
      + "\ngetX3 cannot be resolved"
      + "\ngetV3 cannot be resolved"
      + "\ngetX1 cannot be resolved"
      + "\ngetX2 cannot be resolved"
      + "\ngetX3 cannot be resolved");
  }
}
